export const tags = [
    "Mmorpg",
    "Shooter",
    "Strategy",
    "Moba",
    "Racing",
    "Sports",
    "Social",
    "Sandbox",
    "Open world",
    "Survival",
    "Pvp",
    "Pve",
    "Pixel",
    "Voxel",
    "Zombie",
    "Turn based",
    "First person",
    "Third person",
    "Top down",
    "Tank",
    "Space",
    "Sailing",
    "Side scroller",
    "Superhero",
    "Permadeath",
    "Card",
    "Battle royale",
    "Mmo",
    "Mmofps",
    "Mmotps",
    "3d",
    "2d",
    "Anime",
    "Fantasy",
    "Sci fi",
    "Fighting",
    "Action rpg",
    "Action",
    "Military",
    "Martial arts",
    "Flight",
    "Low spec",
    "Tower defense",
    "Horror",
    "Mmorts",
];

export const platforms = ["PC", "Browser", "All"];

export const sortBy = [
    "Release date",
    "Popularity",
    "Alphabetical",
    "Relevance",
];
